# Generated by Django 4.0.4 on 2022-05-03 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_alter_itineraire_altitude_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_depart',
            field=models.PositiveIntegerField(verbose_name='Altitude de départ (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_maximale',
            field=models.PositiveIntegerField(verbose_name='Altitude maximale (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_minimale',
            field=models.PositiveIntegerField(verbose_name='Altitude minimale (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_negatif_cumule',
            field=models.PositiveIntegerField(verbose_name='Dénivelé négatif cumulé (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_positif_cumule',
            field=models.PositiveIntegerField(verbose_name='Dénivelé positif cumulé (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='duree',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée (en heure)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(verbose_name='Date de la sortie'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='difficulte_ressentie',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Difficulté ressentie (de 1 à 5)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='experience',
            field=models.CharField(choices=[('Tous débutants', 'Tous débutants'), ('Tous expérimentés', 'Tous expérimentés'), ('Mixte', 'Mixte')], max_length=20, verbose_name='Expérience du groupe'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='meteo',
            field=models.CharField(choices=[('Bonne', 'Bonne'), ('Moyenne', 'Moyenne'), ('Mauvaise', 'Mauvaise')], max_length=20, verbose_name='Météo'),
        ),
    ]
