# Generated by Django 4.0.4 on 2022-04-25 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0002_alter_itineraire_altitude_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.CharField(max_length=20, verbose_name='Date de la sortie'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='difficulte_ressentie',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Difficulté ressentie (de 1 à 5)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='experience',
            field=models.CharField(choices=[('Tous débutants', 'Tous débutants'), ('Tous expérimentés', 'Tous expérimentés'), ('Mixte', 'Mixte')], max_length=20, verbose_name='Expérience du groupe'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='meteo',
            field=models.CharField(choices=[('Bonne', 'Bonne'), ('Moyenne', 'Moyenne'), ('Mauvaise', 'Mauvaise')], max_length=20, verbose_name='Météo'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date commentaire')),
                ('texte', models.TextField()),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.sortie')),
                ('utilisateur_auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
