# Generated by Django 4.0.4 on 2022-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_alter_itineraire_altitude_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='duree_reelle',
            field=models.IntegerField(verbose_name='Durée réelle (en heure)'),
        ),
    ]
