# Generated by Django 4.0.4 on 2022-04-25 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0005_alter_commentaire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sortie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itineraires.sortie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 15, 10, 19, 313914)),
        ),
    ]
