# Generated by Django 4.0.4 on 2022-04-25 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0006_photo_sortie_alter_commentaire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 16, 22, 12, 781400)),
        ),
    ]
