# Generated by Django 4.0.4 on 2022-05-02 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0007_alter_commentaire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 9, 11, 28, 876700)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 9, 11, 28, 876700)),
        ),
    ]
