# Generated by Django 4.0.4 on 2022-05-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_itineraire_latitude_arrivee_and_more'),
        ('itineraires', '0004_alter_sortie_duree_reelle'),
        ('itineraires', '0008_commentaire_statut_alter_commentaire_date_and_more'),
    ]

    operations = [
    ]
