# Generated by Django 4.0.4 on 2022-05-04 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0009_merge_20220504_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 14, 45, 2, 521480)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 14, 45, 2, 521883)),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(verbose_name='Date de la sortie'),
        ),
    ]
