# Generated by Django 4.0.4 on 2022-05-04 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0010_alter_commentaire_date_alter_photo_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 15, 58, 28, 419959)),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_arrivee',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Latitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_depart',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Latitude point de départ'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_arrivee',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Longitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_depart',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Longitude point de départ'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 15, 58, 28, 420401)),
        ),
    ]
