# Generated by Django 4.0.4 on 2022-05-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0011_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 16, 4, 26, 636329)),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_arrivee',
            field=models.FloatField(verbose_name='Latitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_depart',
            field=models.FloatField(verbose_name='Latitude point de départ'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_arrivee',
            field=models.FloatField(verbose_name='Longitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_depart',
            field=models.FloatField(verbose_name='Longitude point de départ'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 16, 4, 26, 636743)),
        ),
    ]
