# Generated by Django 4.0.4 on 2022-05-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0009_merge_20220504_1654'),
        ('itineraires', '0014_alter_commentaire_date_and_more'),
    ]

    operations = [
    ]
