# Generated by Django 4.0.4 on 2022-05-05 09:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0015_merge_20220505_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 9, 0, 213613)),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='duree',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (en heure)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_arrivee',
            field=models.FloatField(verbose_name='Latitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_depart',
            field=models.FloatField(verbose_name='Latitude point de départ'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_arrivee',
            field=models.FloatField(verbose_name='Longitude point arrivée'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_depart',
            field=models.FloatField(verbose_name='Longitude point de départ'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 9, 0, 214610)),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Date de la sortie'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='duree_reelle',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée réelle (en heure)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='nombre_personne',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de personnes ayant réalisé la sortie'),
        ),
    ]
