# Generated by Django 4.0.4 on 2022-05-05 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0016_alter_commentaire_date_alter_itineraire_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 23, 26, 957598)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 23, 26, 958005)),
        ),
    ]
